<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <RepositoryUrl>https://github.com/luingry/WinputLan</RepositoryUrl>
    <Company>luingry</Company>
    <Product>Winput LAN</Product>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</Version>
  </PropertyGroup>
</Project>
